[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_bessy_anchor = "5n7caz2oaSQb8yunT7Mcee48W5uBHS3V6v1FhByiVTf9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/topher/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
